# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55df3e5dce3a32ae96a23bc8ecdcc2eced9abef0d2cb7f1d49e4e69eb22b9c1095ff72fe9de44d50cf0a83b5d3ccb21e3962a8a055e93a98cc3289965325108e

test:
  secret_key_base: de94e70c47681d985182146d3d4b10c108ada783a9b910c9e34fb3f0534b475467847137bbaab41718b4f8ce48c4bac5fc280d83fec6ba466d5f3046ec25c051

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
